### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by windbender** [TomCools/dropwizard-websocket-jee7-bundle#3]
Some of us, because of hovering corporate lawyers, need to be cautious about the licenses in the software we use.  It would be very helpful to have a license file in this repository.    Thanks!

**Comment by TomCools** [comment]
Dear Windbender,

Thank you for raising this issue. I will look at it this evening or somewhere this weekend. 

Tom

**Comment by TomCools** [comment]
Hi Windbender. I have added the LICENSE file. I didn't know i had to explicity add one to the project, since i had added the licence-tag in the POM file.

**Comment by windbender** [comment]
I was looking in the POM and saw that.   Honestly, I don't know if there is any legal precedent around this, but I figured a license file doesn't take long.   Thanks!!!
